import { Inter } from 'next/font/google';
import Image from 'next/image';
import dynamicLoader from 'next/dynamic';
import Loading from '../components/Shared/Loading';
import { useRouter } from 'next/router'; 

const inter = Inter({ subsets: ['latin'] })

const defaultJson = { 
maxTimeToFinish: 3600,
showTimerPanel: "bottom",
showProgressBar: "top",
progressBarType: "questions",
"title":"About Near Blockchain","description":"Survey generated by AI - 2023-07-31T03:27:57.885Z","logo":"https://qstn.open4glabs.xyz/assets/images/survey_icon.png","pages":[{"name":"What consensus algorithm does Near use?","title":"What consensus algorithm does Near use?","elements":[{"name":"What consensus algorithm does Near use?","title":"What consensus algorithm does Near use?","type":"RADIOGROUP","points":1,"choices":[{"value":"Proof of Work"},{"value":"Proof of Stake"},{"value":"Practical Byzantine Fault Tolerance"},{"value":"Delegated Proof of Stake"}],"isRequired":true,"correctAnswer":null}]},{"name":"What is the primary goal of Near?","title":"What is the primary goal of Near?","elements":[{"name":"What is the primary goal of Near?","title":"What is the primary goal of Near?","type":"RADIOGROUP","points":1,"choices":[{"value":"To become a global payment platform"},{"value":"To become the most secure blockchain"},{"value":"To provide a high-performance blockchain for decentralized applications"},{"value":"To become the most widely adopted blockchain"}],"isRequired":true,"correctAnswer":null}]},{"name":"How does Near's consensus algorithm ensure finality?","title":"How does Near's consensus algorithm ensure finality?","elements":[{"name":"How does Near's consensus algorithm ensure finality?","title":"How does Near's consensus algorithm ensure finality?","type":"RADIOGROUP","points":1,"choices":[{"value":"By using a hybrid consensus algorithm"},{"value":"By using a proof of stake consensus algorithm"},{"value":"By using a proof of work consensus algorithm"},{"value":"By using a practical Byzantine Fault Tolerance algorithm"}],"isRequired":true,"correctAnswer":null}]},{"name":"What is the native cryptocurrency of the Near network?","title":"What is the native cryptocurrency of the Near network?","elements":[{"name":"What is the native cryptocurrency of the Near network?","title":"What is the native cryptocurrency of the Near network?","type":"RADIOGROUP","points":1,"choices":[{"value":"BTC"},{"value":"ETH"},{"value":"SOL"},{"value":"XRP"}],"isRequired":true,"correctAnswer":null}]},{"name":"What type of smart contracts does Near support?","title":"What type of smart contracts does Near support?","elements":[{"name":"What type of smart contracts does Near support?","title":"What type of smart contracts does Near support?","type":"RADIOGROUP","points":1,"choices":[{"value":"Ethereum-based smart contracts"},{"value":"Solidity-based smart contracts"},{"value":"Tendermint-based smart contracts"},{"value":"WebAssembly-based smart contracts"}],"isRequired":true,"correctAnswer":null}]},{"name":"What is the primary benefit of Near's architecture?","title":"What is the primary benefit of Near's architecture?","elements":[{"name":"What is the primary benefit of Near's architecture?","title":"What is the primary benefit of Near's architecture?","type":"RADIOGROUP","points":1,"choices":[{"value":"Low latency"},{"value":"High scalability"},{"value":"Highly secure"},{"value":"Low transaction fees"}],"isRequired":true,"correctAnswer":null}]},{"name":"What programming language is used to develop smart contracts on Near?","title":"What programming language is used to develop smart contracts on Near?","elements":[{"name":"What programming language is used to develop smart contracts on Near?","title":"What programming language is used to develop smart contracts on Near?","type":"RADIOGROUP","points":1,"choices":[{"value":"Solidity"},{"value":"Go"},{"value":"Rust"},{"value":"JavaScript"}],"isRequired":true,"correctAnswer":null}]},{"name":"What is the maximum block size on the Near network?","title":"What is the maximum block size on the Near network?","elements":[{"name":"What is the maximum block size on the Near network?","title":"What is the maximum block size on the Near network?","type":"RADIOGROUP","points":1,"choices":[{"value":"512 MB"},{"value":"256 MB"},{"value":"128 MB"},{"value":"64 MB"}],"isRequired":true,"correctAnswer":null}]},{"name":"How many transactions can Near process per second?","title":"How many transactions can Near process per second?","elements":[{"name":"How many transactions can Near process per second?","title":"How many transactions can Near process per second?","type":"RADIOGROUP","points":1,"choices":[{"value":"500"},{"value":"1000"},{"value":"3500"},{"value":"7500"}],"isRequired":true,"correctAnswer":null}]},{"name":"How is the Near network secured?","title":"How is the Near network secured?","elements":[{"name":"How is the Near network secured?","title":"How is the Near network secured?","type":"RADIOGROUP","points":1,"choices":[{"value":"By using a proof of stake consensus algorithm"},{"value":"By using a proof of work consensus algorithm"},{"value":"By using a delegated proof of stake consensus algorithm"},{"value":"By using a practical Byzantine Fault Tolerance algorithm"}],"isRequired":true,"correctAnswer":null}]}]};


const SurveyComponent = dynamicLoader(
  () => import('../components/Quiz'),
  {
    loading: () => <Loading />,
    ssr: false
  }
);

export default function Quiz() {
  const router = useRouter();

  const onComplete = (surveyModel: any) => {
    console.log(surveyModel);
    setTimeout(() => router.push('/reward'), 2000);
    return;
  }

  return (
    <main className={`${inter.className}`}>
      <div className="relative flex sm:min-h-screen min-h-full flex-col justify-center overflow-hidden bg-gray-50 sm:py-12">
        <Image src="/img/beams.jpg" alt="" className="absolute top-1/2 left-1/2 max-w-none -translate-x-1/2 -translate-y-1/2" width={1308} height={1200} />
        <div className="absolute inset-0 bg-[url(/img/grid.svg)] bg-center [mask-image:linear-gradient(180deg,white,rgba(255,255,255,0))]"></div>
        <div className="relative sm:bg-white sm:pt-5 sm:pb-4 shadow-xl ring-1 ring-gray-900/5 sm:mx-auto sm:max-w-lg sm:rounded-lg sm:px-10">
          <div className="mx-auto max-w-full">
            <div className="flex flex-col p-3 mt-48">
              <SurveyComponent surveyJson={defaultJson} onComplete={onComplete} />
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}